# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6eeae73eaeea8a6700fd21205c40866a8a46028e37fb20b2914925de4f53ea7276bc68788ada827974fa1eb60b400ed1c91838e3f710e0370050c6766c35930

test:
  secret_key_base: bc61394d5b13fb679ef3c6b9895cacf230005e4057427936a0f7eda07bed07ddd49b16809e18b84fa9b16a9421743d98acd1e2c7264bc717b6161efe8042633a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
